name: Run cron

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
      with:
          persist-credentials: false
    - name: Use Node16
      uses: actions/setup-node@v3
      with:
        node-version: '16.15.1'
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
    - name: Running script now
      run: node dist/cron.js
      env:
        MONGO_DB: ${{ secrets.MONGO_DB }}